### ISSUE TITLE
File upload disallowed?

### ISSUE THREAD

**Issue by stevepiercy** [plone/demo.plone.org#8] opened 2022-12-23 03:32 UTC
I cannot upload an image to a hero block or image block. The response is a 401:

```json
{
  "message": "You are not authorized to access this resource.",
  "type": "Unauthorized"
}
```

**Comment by davisagli** [comment] 2023-01-23 01:38
@stevepiercy I can't reproduce this on demo.plone.org, so I guess either it was fixed or it is a consequence of particular circumstances. Closing, feel free to reopen with more detailed steps to reproduce if it is still an issue.

**Closed** 2023-01-23 01:39 UTC

**Comment by stevepiercy** [comment] 2023-01-23 03:05
Huh, yeah, it works for me now, too. Maybe I hit it during a reset?

**Comment by davisagli** [comment] 2023-01-23 03:06
That could explain it
